name: ReactJS CI
run-name: ${{ github.actor }} is starting the execution of backend pipeline "ReactJS CI" with GitHub Actions
on:
  push:
    branches: [ "develop", "feature/**" ]
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
jobs:
  build:
    name: 'Front CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 17 for x64
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          architecture: 'x64'
      - name: Install Node Modules
        run: npm install
      - name: Execute CI of Front Component
        run: npm ci
#      - name: Test Front Component
#        run: npm test
