name: ReactJS Deployment Removal
run-name: ${{ github.actor }} is starting the execution of backend pipeline "ReactJS Deployment Removal" with GitHub Actions
on:
#  push:
#    branches: [ "develop", "feature/**" ]
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
jobs:
  build:
    name: 'Front Deployment Removal'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Remove Static Content from S3
        run: aws s3 rm s3://my-s3-bucket-extau3 --recursive
